# Generated by Django 5.0 on 2025-11-23 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('talkmaniaApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.admin'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='talkmaniaApp.hotel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='talkmaniaApp.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='talkmaniaApp.hotel'),
        ),
        migrations.AddField(
            model_name='reserva_habitacion',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.habitacion'),
        ),
        migrations.AddField(
            model_name='reserva_habitacion',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='talkmaniaApp.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talkmaniaApp.tipo_pago'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva_habitacion',
            unique_together={('reserva', 'habitacion')},
        ),
    ]
