# Generated by Django 5.0 on 2025-11-24 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkmaniaApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='admin',
            field=models.ForeignKey(limit_choices_to={'rol': 'administrador'}, on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
